name: fetch-data-dev
channels:
  - conda-forge
dependencies:
  - python=3.8
  ############## These will have to be adjusted to your specific project
  - numpy
  - pooch
  - numpydoc
  - sphinx
  - sphinx_rtd_theme
  - ipython
  - nbconvert
  - nbformat
  - ipykernel
  - pandoc
  - joblib
  ##############
  - pytest
  - pip
  - pip:
    - codecov
    - requests
    - chardet==3.0.4
    - aiohttp
    - fsspec
    - pytest-cov
    - pre-commit
    - coverage[toml]
    - recommonmark
    - python-dotenv
    - envyaml
    - docrep<=0.2.7
    - nbsphinx
    - jupyter_client
    - sphinx_pangeo_theme
    - sphinx-copybutton
    - sphinxcontrib-srclinks
