name: fetch-data
channels:
  - conda-forge
dependencies:
  # Required for full project functionality (don't remove)
  - pytest
  # Examples (remove and add as needed)
  - numpy
  - pandas
  - pooch
  - fsspec
  - pip:
    - python-dotenv
    - aiohttp
    - envyaml
    - datetime_matcher
